### PR TITLE
Feature/copy

### PR DESCRIPTION
**Pull request by wangtuanjie**

### CODE REVIEW

**Comment by xiang90** [comment]
why closed?

**Comment by wangtuanjie** [comment]
Too junk commits

**Comment by xiang90** [comment]
@wangtuanjie Ah... no worries... you need to go through code review anyway. so you can simply wait until the code review get done.

**Comment by yutongp** [comment]
for `copy` api, are we gonna make copy file within one node and copy file between different node the same one?

**Comment by xiang90** [comment]
@yutongp We should rename it to pull probably? The main use case would be copying from one node to another i think

**Comment by yichengq** [comment]
@wangtuanjie: We discussed around the copy command a little, and doubt whether it is useful as an API. There is no common usage for local copy in distributed fs scenario. If this happens rarely, we can let user read all file and write it back.

Remote copy may be helpful. One example is that user may need to copy file from one cfs to another for reconstruct. But this may have been covered by reconstruct workflow. /cc @tnachen

**Comment by wangtuanjie** [comment]
@yichengq I understand your meaning and will close the pr.

**Comment by wangtuanjie** [comment]
@yichengq I Confuse with the issue https://github.com/c-fs/cfs/issues/31 meaning

**Pull request closed without merging**
